### ISSUE TITLE
Updates/deletes to profile settings are not shown in the response

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/onboarding-processor#14]
**Steps**
Go to any users profile settings : https://www.topcoder-dev.com/settings/profile/
Update/delete an existing trait (ex- bio)
Call {{URL}}/members//traits?traitIds=onboarding_checklist API
See the response

the updated/deleted data are still displayed as true in the response

example user: taasintake6
Deleted data - bio & skills

**Comment by vikasrohit** [comment]
@Schpotsky separate PR for each issue would be better, but if single PR makes your life easy, go ahead with that as well. It is not strict yet.
For branch please use develop branch for base work. You can create PR against develop as well as it is not feature now.

**Comment by vikasrohit** [comment]
Thanks @Schpotsky for the quick turnaround. `skills` is something we can not do much here without an event, agreed.

**Comment by vikasrohit** [comment]
@sdgun please log the skill deletion issue as separate issue now to track it better. As this seems to be a fairly rare use case, we can handle it after the release.

**Comment by sdgun** [comment]
Created https://github.com/topcoder-platform/onboarding-processor/issues/31
