### ISSUE TITLE
Remove title field for now from the profile completeness check

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/onboarding-processor#18]
As we don't have the field to capture the title in member profile, it does not make sense to keep counting the title field for the completeness of the profile.

**Comment by sdgun** [comment]
Verified in Dev, title field is removed from the response.

![image](https://user-images.githubusercontent.com/4592712/136888469-c0dfdd39-a163-43d1-aae3-fd540b5786e2.png)

**Comment by sdgun** [comment]
Verified in prod.

![image](https://user-images.githubusercontent.com/4592712/137088796-76586525-4ff6-453e-ba91-ffa1379bdcee.png)
