### ISSUE TITLE
Add address to the profile completeness onboarding step check

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/onboarding-processor#19]
We missed to add this while building profile completeness check.

**Comment by vikasrohit** [comment]
@veshu please make sure we consider all address fields which are mandatory on the UI for a user to fill, when checking if the address is filled or not.

**Comment by Schpotsky** [comment]
@vikasrohit ,

The message generated by [member-api](https://github.com/topcoder-platform/member-api) when updating member profile has the following structure:

```json
{
  "topic":"member.action.profile.update",
  "originator":"topcoder-member-api",
  "timestamp":"2021-10-11T11:52:31.968Z",
  "mime-type":"application/json",
  "payload":{
    "lastName":"last name",
    "addresses":[
      {
        "streetAddr1":"GM INFINITE ECITY TOWN",
        "streetAddr2":"Street Address 2",
        "city":"Bangalore",
        "stateCode":"Karnataka",
        "zip":"560110",
        "type":"HOME"
      }
    ],
    "updatedBy":"LEyCiuOrHc7UAFoY0EAAhMulWSX7SrQ5@clients",
    "description":"What goes around comes around",
    "homeCountryCode":"IRL",
    "handle":"denis",
    "otherLangName":"en",
    "userId":123,
    "handleLower":"denis",
    "emailVerifyTokenDate":"2021-10-11T12:52:31.881Z",
    "tracks":[
      "DESIGN",
      "DEVELOP"
    ],
    "firstName":"Atif Ali",
    "photoURL":"https://topcoder-dev-media.s3.amazonaws.com/member/profile/upbeat-1575621848253.png",
    "createdAt":"2020-02-06T07:38:50.088Z",
    "createdBy":"test1",
    "newEmailVerifyToken":"0414ee2a-5817-4015-ab13-91a5470db448",
    "emailVerifyToken":"500d0696-79ab-41ea-9cbd-de2f274a4bfb",
    "maxRating":{
      "rating":1000,
      "track":"dev",
      "subTrack":"code"
    },
    "newEmail":"atif.siddiqui2@topcoder.com",
    "competitionCountryCode":"IRL",
    "newEmailVerifyTokenDate":"2021-10-11T12:52:31.881Z",
    "email":"denis@topcoder.com",
    "status":"ACTIVE",
    "updatedAt":1633953151881
  }
}
```

1. Is the `addresses` array (in the message) expected to hold more than one item ? (In the UI there is only one single address instance)

2. If there are multiple addresses in the array, do we need to check all of them or only the first one.

3. To consider the address complete, we need to check all the following items: `streetAddr1`, `streetAddr2`, `city`,  `stateCode`, `zip` , (Not sure about the `type` field)

4. For country there are two country related fields in the message: `homeCountryCode`, `competitionCountryCode`, which one should it be considered for the address completeness

**Comment by sdgun** [comment]
Verified in Dev, country is set to true for users on saving profile settings.
