### ISSUE TITLE
Update Tax Form Receiver to generate v5 bus events for docusign document completion events

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/onboarding-processor#3]
## Overview
In this challenge, we will update the https://github.com/topcoder-platform/terms-receiver, to parse the DocuSign envelope and raise a new event on Topcoder bus

## Objective
As criteria to receive the payments by a member from Topcoder, the member has to submit the tax form, please check https://www.topcoder.com/thrive/articles/payment-policies-and-instructions for more detail. For this, we are using DocuSign. There are two types of tax form  W-9 or a W-8BEN. When the member submits the tax form, DocuSign calls our webhook at `terms-receiver` code base. Since these forms are embedded on the Topcoder platform using legacy codebase, we don’t have mapping terms set up on the database. But we need a way to update member traits whether the member has submitted the tax form or not.

For this, we will update the DocuSign webhook handler to capture whether the form submitted are related to Tax form or not. If they are related to tax then raise the `terms.notification.user.taxform.updated`

## Individual Requirements
- Update the `services/DocusignService.js`
- After Line number 82, we need to check `DocumentStatuses[0].DocumentStatus[0].TemplateName` on the webhook payload whether the values are `W-9(TopCoder)` or `W-8BEN(TopCoder)`. If the name is either of them, then raise the event with following payload 
   
```
userId: The topcoder user Id based on user email
taxForm: DocumentStatuses[0].DocumentStatus[0].TemplateName
Handle: topcoder handle
created: new Date()

```
- The template name should be configurable
- The event name should be configurable 
- Provide guidance on how to test this

**Comment by vikasrohit** [comment]
PR generated https://github.com/topcoder-platform/terms-receiver/pull/1

**Comment by vikasrohit** [comment]
Updated terms-receiver to read correct email address, it was reading email of the document owner instead of the recipient.

**Comment by sdgun** [comment]
Verified in Dev by signing in for both W-9 and W-8BEN. Calling traits endpoint with parameter onboarding_checklist returned response as expected.
