### ISSUE TITLE
Remove strict validation from legacyId for terms event payload

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/onboarding-processor#32]
We are seeing too many instances of following error:

<img width="1108" alt="Screen Shot 2021-10-13 at 11 10 10 AM" src="https://user-images.githubusercontent.com/2417632/137073762-325feffa-349b-4cfc-b6c7-8396f9722664.png">

We should get rid of mandatory `legacyId` validation for the terms event as we are not using the `legacyId` anywhere in our process.

**Comment by veshu** [comment]
> @veshu I have assigned the task to @Schpotsky as well, in case he is able to work on this.

sure
